# Generated by Django 4.2.25 on 2025-10-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='energy_restore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='is_food',
            field=models.BooleanField(default=False),
        ),
    ]
