# Generated by Django 4.2.25 on 2025-10-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_material_energy_restore_material_is_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcell',
            name='location_description',
            field=models.TextField(blank=True, default='Zone inconnue'),
        ),
        migrations.AddField(
            model_name='mapcell',
            name='osm_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_x',
            field=models.FloatField(default=4.893),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_y',
            field=models.FloatField(default=44.933),
        ),
    ]
