# Generated by Django 4.2.25 on 2025-10-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_mapcell_location_description_mapcell_osm_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🔨', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='required_workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='game.workstation'),
        ),
        migrations.CreateModel(
            name='PlayerWorkstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='game.player')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.workstation')),
            ],
            options={
                'unique_together': {('player', 'workstation')},
            },
        ),
    ]
