# Generated by Django 4.2.25 on 2025-10-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_workstation_recipe_required_workstation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TalentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('tier', models.IntegerField(default=1)),
                ('xp_required', models.IntegerField(default=0)),
                ('prereq_codes', models.JSONField(blank=True, default=list)),
                ('effect_type', models.CharField(max_length=100)),
                ('effect_value', models.IntegerField(default=0)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents', to='game.skill')),
            ],
            options={
                'unique_together': {('skill', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PlayerTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents', to='game.player')),
                ('talent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.talentnode')),
            ],
            options={
                'unique_together': {('player', 'talent_node')},
            },
        ),
        migrations.CreateModel(
            name='PlayerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('xp_to_next', models.IntegerField(default=50)),
                ('total_xp', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='game.player')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.skill')),
            ],
            options={
                'unique_together': {('player', 'skill')},
            },
        ),
    ]
