# Generated by Django 4.2.25 on 2025-10-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_skill_talentnode_playertalent_playerskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='durability_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='durability_max',
            field=models.IntegerField(default=0),
        ),
    ]
