# Generated by Django 4.2.25 on 2025-10-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_inventory_durability_current_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'material')},
        ),
    ]
