# Generated by Django 4.2.25 on 2025-11-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_add_initial_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='equipment_slot',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('main_hand', 'Main Hand'), ('off_hand', 'Off Hand'), ('accessory', 'Accessory')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_equipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='speed_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EquippedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('main_hand', 'Main Hand'), ('off_hand', 'Off Hand'), ('accessory', 'Accessory')], max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.material')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_items', to='game.player')),
            ],
            options={
                'unique_together': {('player', 'slot')},
            },
        ),
    ]
