# Generated by Django 4.2.25 on 2025-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_material_attack_material_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('minerais', 'Minerais'), ('bois', 'Bois'), ('gemmes', 'Gemmes'), ('magie', 'Magie'), ('nourriture', 'Nourriture'), ('divers', 'Divers')], default='divers', max_length=50),
        ),
    ]
