# Generated by Django 4.2.25 on 2025-11-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='agility',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='luck',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=10),
        ),
    ]
