# Generated by Django 4.2.25 on 2025-11-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_player_agility_player_health_player_intelligence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🐾', max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=20)),
                ('attack', models.IntegerField(default=5)),
                ('defense', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=10)),
                ('biomes_json', models.TextField(default='[]')),
                ('loot_table_json', models.TextField(default='{}')),
            ],
        ),
    ]
