# Generated by Django 4.2.25 on 2025-11-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_achievement_playerachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerachievement',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='game.player'),
        ),
    ]
