# Generated by Django 4.2.25 on 2025-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_playerachievement_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_moves',
            field=models.IntegerField(default=0),
        ),
    ]
