# Generated by Django 4.2.25 on 2025-11-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_player_total_moves'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏠', max_length=50)),
                ('category', models.CharField(choices=[('housing', 'Housing'), ('production', 'Production'), ('storage', 'Storage'), ('defense', 'Defense'), ('decoration', 'Decoration')], default='housing', max_length=20)),
                ('energy_regeneration_bonus', models.IntegerField(default=0, help_text='Energy regen per hour')),
                ('storage_bonus', models.IntegerField(default=0, help_text='Additional storage slots')),
                ('defense_bonus', models.IntegerField(default=0, help_text='Defense against attacks')),
                ('production_bonus', models.FloatField(default=0.0, help_text='% boost to crafting/gathering')),
                ('construction_time', models.IntegerField(default=60, help_text='Time in seconds to build')),
                ('required_level', models.IntegerField(default=1, help_text='Player level required')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under_construction', 'Under Construction'), ('completed', 'Completed'), ('damaged', 'Damaged'), ('destroyed', 'Destroyed')], default='under_construction', max_length=20)),
                ('health', models.IntegerField(default=100)),
                ('max_health', models.IntegerField(default=100)),
                ('construction_started_at', models.DateTimeField(auto_now_add=True)),
                ('construction_completed_at', models.DateTimeField(blank=True, null=True)),
                ('construction_progress', models.IntegerField(default=0, help_text='Percentage completed')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.buildingtype')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.mapcell')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.player')),
            ],
            options={
                'ordering': ['-construction_started_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_materials', to='game.buildingtype')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.material')),
            ],
            options={
                'unique_together': {('building_type', 'material')},
            },
        ),
    ]
