# Generated by Django 4.2.25 on 2025-11-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_buildingtype_building_buildingrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_energy_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(choices=[('gather_count', 'Gather Count'), ('craft_count', 'Craft Count'), ('move_count', 'Move Count'), ('level_reached', 'Level Reached'), ('material_collected', 'Material Collected'), ('recipe_crafted', 'Recipe Crafted'), ('biome_visited', 'Biome Visited'), ('mob_defeated', 'Mob Defeated'), ('building_count', 'Building Count'), ('building_constructed', 'Building Constructed')], max_length=30),
        ),
    ]
