# Generated by Django 5.2.8 on 2025-11-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_house_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='aggression_level',
            field=models.CharField(choices=[('passive', 'Passive'), ('neutral', 'Neutral'), ('aggressive', 'Aggressive')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='mob',
            name='spawn_rate',
            field=models.FloatField(default=0.3, help_text='Probability of spawning (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CombatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('victory', 'Victory'), ('fled', 'Fled'), ('defeated', 'Defeated')], max_length=20)),
                ('damage_dealt', models.IntegerField(default=0)),
                ('damage_taken', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('xp_gained', models.IntegerField(default=0)),
                ('loot_json', models.TextField(default='[]')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mapcell')),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mob')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_logs', to='game.player')),
            ],
        ),
    ]
