# Generated by Django 4.2.25 on 2025-11-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_mob_aggression_level_mob_spawn_rate_alter_house_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='hunger_restore',
            field=models.IntegerField(default=0, help_text='Hunger restored when consumed'),
        ),
        migrations.AddField(
            model_name='material',
            name='max_durability',
            field=models.IntegerField(default=0, help_text='0 = infinite durability'),
        ),
        migrations.AddField(
            model_name='material',
            name='radiation_change',
            field=models.IntegerField(default=0, help_text='Radiation change (negative = reduces)'),
        ),
        migrations.AddField(
            model_name='material',
            name='thirst_restore',
            field=models.IntegerField(default=0, help_text='Thirst restored when consumed'),
        ),
        migrations.AddField(
            model_name='material',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Weight in kg'),
        ),
        migrations.AddField(
            model_name='material',
            name='weight_capacity_bonus',
            field=models.FloatField(default=0.0, help_text='Backpack/bag capacity bonus'),
        ),
        migrations.AddField(
            model_name='player',
            name='hunger',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='last_hunger_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_thirst_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='max_carry_weight',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='player',
            name='max_hunger',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='max_thirst',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='radiation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='thirst',
            field=models.IntegerField(default=100),
        ),
    ]
