# Generated by Django 4.2.25 on 2025-11-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_material_hunger_restore_material_max_durability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('durability_current', models.IntegerField(default=0)),
                ('durability_max', models.IntegerField(default=0)),
                ('dropped_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Item disappears after this time', null=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_items', to='game.mapcell')),
                ('dropped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_dropped', to='game.player')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.material')),
            ],
            options={
                'ordering': ['-dropped_at'],
            },
        ),
    ]
