# Generated by Django 4.2.25 on 2025-11-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_droppeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🚲', max_length=50)),
                ('carry_bonus', models.FloatField(default=0.0, help_text='Additional carry capacity in kg')),
                ('speed_bonus', models.IntegerField(default=0, help_text='Speed bonus (reduces travel time/energy)')),
                ('energy_efficiency', models.IntegerField(default=0, help_text='Percentage reduction in move energy cost')),
                ('max_durability', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durability_current', models.IntegerField(default=100)),
                ('is_equipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='game.player')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_by', to='game.playervehicle'),
        ),
    ]
