# Generated by Django 4.2.25 on 2025-11-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_vehicle_playervehicle_player_current_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='health_restore',
            field=models.IntegerField(default=0, help_text='Health restored when consumed'),
        ),
    ]
