# Generated by Django 4.2.25 on 2025-11-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_material_health_restore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='icon',
            field=models.TextField(default='🔹'),
        ),
    ]
