# Generated by Django 4.2.25 on 2025-11-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_material_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='👕', max_length=50)),
                ('defense', models.IntegerField(default=0, help_text='Defense provided')),
                ('weight', models.FloatField(default=0.0, help_text='Weight of the clothing')),
                ('slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('accessory', 'Accessory')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🗡️', max_length=50)),
                ('attack', models.IntegerField(default=0, help_text='Attack power')),
                ('defense', models.IntegerField(default=0, help_text='Defense value')),
                ('weight', models.FloatField(default=0.0, help_text='Weight for encumbrance')),
                ('slot', models.CharField(choices=[('main_hand', 'Main Hand'), ('off_hand', 'Off Hand'), ('both_hands', 'Both Hands')], default='main_hand', max_length=20)),
            ],
        ),
    ]
