# Generated by Django 4.2.25 on 2025-11-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_add_database_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameconfig',
            options={'ordering': ['key'], 'verbose_name': 'Game Configuration', 'verbose_name_plural': 'Game Configurations'},
        ),
        migrations.RemoveIndex(
            model_name='cellmaterial',
            name='game_cellmat_cell_material_idx',
        ),
        migrations.RemoveIndex(
            model_name='cellmaterial',
            name='game_cellmat_quantity_idx',
        ),
        migrations.RemoveIndex(
            model_name='craftinglog',
            name='game_craftlog_player_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='craftinglog',
            name='game_craftlog_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='droppeditem',
            name='game_droppeditem_cell_idx',
        ),
        migrations.RemoveIndex(
            model_name='droppeditem',
            name='game_droppeditem_player_idx',
        ),
        migrations.RemoveIndex(
            model_name='gatheringlog',
            name='game_gatherlog_player_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='gatheringlog',
            name='game_gatherlog_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='game_inventory_player_material_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='game_inventory_quantity_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapcell',
            name='game_mapcell_grid_xy_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapcell',
            name='game_mapcell_biome_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='game_material_rarity_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='game_material_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='game_material_is_food_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='game_material_is_equipment_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='game_player_grid_xy_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='game_player_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='game_player_energy_update_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerskill',
            name='game_playerskill_player_skill_idx',
        ),
        migrations.RemoveIndex(
            model_name='playertalent',
            name='game_playertalent_player_node_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='game_recipe_result_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipeingredient',
            name='game_recipeingred_recipe_mat_idx',
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Last time this configuration was modified'),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of what this configuration does'),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='key',
            field=models.CharField(help_text='Configuration key (unique identifier)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='value',
            field=models.TextField(help_text='Configuration value (can be JSON for complex values)'),
        ),
    ]
