# Generated by Django 5.2.8 on 2025-11-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_add_gameconfig_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0, help_text="Player's currency in coins"),
        ),
    ]
