# Generated by Django 5.2.8 on 2025-11-26 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_player_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏪', max_length=50)),
                ('biome', models.CharField(blank=True, help_text='Shop appears only in this biome (empty = all biomes)', max_length=50, null=True)),
                ('buy_price_multiplier', models.FloatField(default=1.0, help_text='Multiplier for buy prices')),
                ('sell_price_multiplier', models.FloatField(default=0.5, help_text='Multiplier for sell prices (player sells to shop)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Achat au magasin'), ('sell', 'Vente au magasin'), ('reward', 'Récompense'), ('quest', 'Quête'), ('achievement', 'Succès'), ('admin', 'Administrateur'), ('other', 'Autre')], max_length=20)),
                ('amount', models.IntegerField(help_text='Positive = gain, negative = loss')),
                ('balance_after', models.IntegerField(help_text='Player balance after transaction')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.material')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='game.player')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.shop')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_buy_price', models.IntegerField(default=10, help_text='Base price for player to buy')),
                ('base_sell_price', models.IntegerField(default=5, help_text='Base price for player to sell to shop')),
                ('stock', models.IntegerField(default=-1, help_text='-1 = unlimited stock')),
                ('max_stock', models.IntegerField(default=-1, help_text='Maximum stock (-1 = no limit)')),
                ('restock_rate', models.IntegerField(default=0, help_text='Items restocked per hour (0 = no restock)')),
                ('last_restock', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('required_level', models.IntegerField(default=1, help_text='Player level required to purchase')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.material')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='game.shop')),
            ],
            options={
                'ordering': ['material__name'],
                'unique_together': {('shop', 'material')},
            },
        ),
    ]
