# Generated by Django 4.2.25 on 2025-11-26 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_shop_transaction_shopitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='credit_card_balance',
            field=models.IntegerField(default=0, help_text="Player's credit card balance (argent en banque)"),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0, help_text="Player's cash money (liquide)"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Achat au magasin'), ('sell', 'Vente au magasin'), ('deposit', 'Dépôt à la banque'), ('withdrawal', 'Retrait à la banque'), ('reward', 'Récompense'), ('quest', 'Quête'), ('achievement', 'Succès'), ('admin', 'Administrateur'), ('other', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏦', max_length=50)),
                ('deposit_fee_percent', models.FloatField(default=0.0, help_text='Fee percentage for deposits (0-100)')),
                ('withdrawal_fee_percent', models.FloatField(default=0.0, help_text='Fee percentage for withdrawals (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='game.mapcell')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
