# Generated by Django 4.2.25 on 2025-11-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_player_credit_card_balance_alter_player_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equippeditem',
            name='slot',
            field=models.CharField(choices=[('head', 'Tête'), ('chest', 'Torse'), ('hands', 'Mains'), ('legs', 'Jambes'), ('feet', 'Pieds'), ('backpack', 'Sac à dos'), ('main_hand', 'Main principale'), ('off_hand', 'Main secondaire'), ('accessory', 'Accessoire')], max_length=20),
        ),
    ]
