# Generated by Django 4.2.25 on 2025-11-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_alter_equippeditem_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('story_text', models.TextField(blank=True, help_text='Narration / contexte de la quête')),
                ('icon', models.CharField(default='📜', max_length=50)),
                ('quest_type', models.CharField(choices=[('gather', 'Récolter'), ('craft', 'Fabriquer'), ('explore', 'Explorer'), ('combat', 'Combat'), ('delivery', 'Livraison'), ('talk', 'Parler')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile'), ('epic', 'Épique')], default='easy', max_length=20)),
                ('required_level', models.IntegerField(default=1, help_text='Niveau minimum requis')),
                ('requirements', models.JSONField(default=dict, help_text="\n    Format: {\n        'gather': [{'material_id': 1, 'quantity': 10}],\n        'craft': [{'recipe_id': 5, 'quantity': 3}],\n        'visit': [{'grid_x': 5, 'grid_y': 10}],\n        'defeat': [{'mob_id': 2, 'quantity': 5}]\n    }\n    ")),
                ('reward_xp', models.IntegerField(default=0)),
                ('reward_money', models.IntegerField(default=0)),
                ('reward_items', models.JSONField(default=list, help_text="[{'material_id': 1, 'quantity': 5}]")),
                ('is_repeatable', models.BooleanField(default=False)),
                ('cooldown_hours', models.IntegerField(default=24, help_text='Hours before quest can be repeated')),
                ('is_active', models.BooleanField(default=True)),
                ('start_npc', models.CharField(blank=True, help_text='PNJ qui donne la quête', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisite_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_quests', to='game.quest')),
            ],
            options={
                'ordering': ['required_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='✨', max_length=50)),
                ('event_type', models.CharField(choices=[('treasure', 'Trésor'), ('merchant', 'Marchand ambulant'), ('danger', 'Danger'), ('resource', 'Ressources abondantes'), ('weather', 'Météo')], max_length=20)),
                ('rewards', models.JSONField(default=dict, help_text="\n    {\n        'xp': 50,\n        'money': 100,\n        'items': [{'material_id': 1, 'quantity': 5}],\n        'gather_multiplier': 2.0\n    }\n    ")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(default=-1, help_text='-1 = unlimited')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.mapcell')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_events', to='game.player')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('active', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('abandoned', 'Abandonnée')], default='available', max_length=20)),
                ('progress', models.JSONField(default=dict, help_text="\n    Format: {\n        'gather': {'material_1': 5, 'material_2': 10},\n        'craft': {'recipe_5': 2},\n        'visit': {'5,10': True},\n        'defeat': {'mob_2': 3}\n    }\n    ")),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('can_repeat_at', models.DateTimeField(blank=True, help_text='When quest can be repeated', null=True)),
                ('times_completed', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='game.player')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_quests', to='game.quest')),
            ],
            options={
                'ordering': ['-accepted_at'],
                'unique_together': {('player', 'quest')},
            },
        ),
    ]
