# Generated by Django 4.2.25 on 2025-11-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_quest_dynamicevent_playerquest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée'), ('completed', 'Complétée'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message optionnel')),
                ('offered_items', models.JSONField(default=list, help_text="[{'material_id': 1, 'quantity': 5}]")),
                ('offered_money', models.IntegerField(default=0)),
                ('requested_items', models.JSONField(default=list, help_text="[{'material_id': 2, 'quantity': 3}]")),
                ('requested_money', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Offre expire après ce temps')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_sent', to='game.player')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('level', 'Niveau'), ('wealth', 'Richesse'), ('gatherer', 'Récolteur'), ('crafter', 'Artisan'), ('explorer', 'Explorateur'), ('combatant', 'Combattant'), ('quests', 'Quêtes')], max_length=20)),
                ('score', models.BigIntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict, help_text="\n    {\n        'level': 15,\n        'total_gathered': 1000,\n        'total_crafted': 500,\n        etc.\n    }\n    ")),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='game.player')),
            ],
            options={
                'ordering': ['category', 'rank'],
                'indexes': [models.Index(fields=['category', 'rank'], name='game_leader_categor_cd2222_idx')],
                'unique_together': {('category', 'player')},
            },
        ),
    ]
