# Generated by Django 4.2.25 on 2025-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_tradeoffer_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='chain_id',
            field=models.CharField(blank=True, help_text='Identifiant de la chaîne de quêtes', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='chain_order',
            field=models.IntegerField(default=0, help_text='Position dans la chaîne (0 = quête indépendante)'),
        ),
    ]
