# Generated by Django 4.2.25 on 2025-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_add_quest_chain_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_daily',
            field=models.BooleanField(default=False, help_text='Quête quotidienne qui se reset automatiquement'),
        ),
    ]
