# Generated by Django 4.2.25 on 2025-11-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_add_daily_quest_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={},
        ),
        migrations.AddField(
            model_name='player',
            name='hydration',
            field=models.FloatField(default=100.0, help_text='Hydration level (0-100), decays slower than thirst'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_drink_time',
            field=models.DateTimeField(blank=True, help_text='When player last drank', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_meal_time',
            field=models.DateTimeField(blank=True, help_text='When player last ate', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='metabolism_rate',
            field=models.FloatField(default=1.0, help_text='Multiplier for hunger/thirst decay (affected by activity)'),
        ),
        migrations.AddField(
            model_name='player',
            name='satiety',
            field=models.FloatField(default=100.0, help_text='Satiety level (0-100), decays slower than hunger'),
        ),
    ]
