# Generated by Django 4.2.25 on 2025-11-27 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_add_realistic_survival_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_proteins', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stored_carbs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stored_fats', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_a_level', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('vitamin_b_complex', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('vitamin_c_level', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('vitamin_d_level', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('vitamin_e_level', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('calcium_level', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('iron_level', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('electrolytes', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('metabolic_rate', models.FloatField(default=1.0, help_text='Overall metabolism speed multiplier')),
                ('body_fat_percentage', models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(50)])),
                ('muscle_mass_kg', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(10)])),
                ('immune_system', models.FloatField(default=100, help_text='Immune strength %, affects disease resistance', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('stamina_regeneration', models.FloatField(default=1.0, help_text='Energy/stamina regen multiplier', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2)])),
                ('healing_rate', models.FloatField(default=1.0, help_text='Health regeneration multiplier', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2)])),
                ('toxin_level', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('food_poisoning', models.BooleanField(default=False)),
                ('last_metabolism_update', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_status', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteins', models.FloatField(default=0, help_text='Protein content (g per 100g)', validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrates', models.FloatField(default=0, help_text='Carbohydrate content (g per 100g)', validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.FloatField(default=0, help_text='Fat content (g per 100g)', validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.FloatField(default=0, help_text='Fiber content (g per 100g)', validators=[django.core.validators.MinValueValidator(0)])),
                ('water', models.FloatField(default=0, help_text='Water content (g per 100g)', validators=[django.core.validators.MinValueValidator(0)])),
                ('calories', models.FloatField(default=0, help_text='Energy content (kcal per 100g)', validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_a', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_b1', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_b2', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_b3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_b6', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_b12', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_c', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_d', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_e', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitamin_k', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('calcium', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('iron', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('magnesium', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('phosphorus', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('potassium', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('zinc', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('digestion_time', models.IntegerField(default=60, help_text='Time to fully digest (minutes)')),
                ('absorption_rate', models.FloatField(default=1.0, help_text='Nutrient absorption efficiency (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('freshness_decay_rate', models.FloatField(default=1.0, help_text='How fast food spoils (higher = faster)')),
                ('is_perishable', models.BooleanField(default=True)),
                ('is_toxic', models.BooleanField(default=False)),
                ('toxicity_level', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='game.material')),
            ],
        ),
        migrations.CreateModel(
            name='DigestingFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('proteins_total', models.FloatField(default=0)),
                ('carbs_total', models.FloatField(default=0)),
                ('fats_total', models.FloatField(default=0)),
                ('calories_total', models.FloatField(default=0)),
                ('vitamins_data', models.JSONField(default=dict, help_text='Vitamin content')),
                ('minerals_data', models.JSONField(default=dict, help_text='Mineral content')),
                ('digestion_start', models.DateTimeField(auto_now_add=True)),
                ('digestion_duration_minutes', models.IntegerField(default=60)),
                ('nutrients_absorbed', models.FloatField(default=0, help_text='Percentage of nutrients absorbed so far', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.material')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digesting_food', to='game.player')),
            ],
            options={
                'ordering': ['digestion_start'],
            },
        ),
    ]
