# Generated by Django 4.2.25 on 2025-11-28 07:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_add_advanced_nutrition_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('body_part_type', models.CharField(choices=[('head', 'Tête'), ('torso', 'Torse'), ('left_arm', 'Bras gauche'), ('right_arm', 'Bras droit'), ('left_leg', 'Jambe gauche'), ('right_leg', 'Jambe droite'), ('left_hand', 'Main gauche'), ('right_hand', 'Main droite'), ('left_foot', 'Pied gauche'), ('right_foot', 'Pied droit')], max_length=20, unique=True)),
                ('critical_multiplier', models.FloatField(default=1.0, help_text='Damage to this part affects overall health by this multiplier')),
                ('base_bleeding_rate', models.FloatField(default=1.0, help_text='How fast this part bleeds when injured')),
                ('can_fracture', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('disease_type', models.CharField(choices=[('infection', 'Infection'), ('virus', 'Virus'), ('bacterial', 'Bactérienne'), ('parasitic', 'Parasitaire'), ('food_poisoning', 'Intoxication alimentaire'), ('radiation_sickness', 'Mal des rayons'), ('common_cold', 'Rhume'), ('flu', 'Grippe'), ('dysentery', 'Dysenterie'), ('cholera', 'Choléra'), ('malaria', 'Paludisme')], max_length=50)),
                ('description', models.TextField()),
                ('base_severity', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progression_rate', models.FloatField(default=1.0, help_text='How fast the disease worsens (per hour)')),
                ('health_drain_rate', models.FloatField(default=0.0, help_text='HP lost per hour')),
                ('stamina_penalty', models.FloatField(default=0.0, help_text='% stamina reduction')),
                ('stat_penalty', models.FloatField(default=0.0, help_text='% reduction to all stats')),
                ('causes_fever', models.BooleanField(default=False)),
                ('causes_vomiting', models.BooleanField(default=False)),
                ('causes_fatigue', models.BooleanField(default=True)),
                ('causes_pain', models.BooleanField(default=False)),
                ('natural_recovery_rate', models.FloatField(default=1.0, help_text='% recovery per hour without treatment')),
                ('requires_medicine', models.BooleanField(default=False)),
                ('is_contagious', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_temperature', models.FloatField(default=37.0, help_text='Body temperature in °C', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(43)])),
                ('heart_rate', models.IntegerField(default=70, help_text='Beats per minute', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('blood_volume', models.FloatField(default=100.0, help_text='Blood volume percentage (100 = full)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('oxygen_level', models.FloatField(default=100.0, help_text='Blood oxygen saturation %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stamina', models.FloatField(default=100.0, help_text='Current stamina level', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_wet', models.BooleanField(default=False)),
                ('wetness_level', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_hypothermic', models.BooleanField(default=False)),
                ('is_hyperthermic', models.BooleanField(default=False)),
                ('exhaustion_level', models.FloatField(default=0.0, help_text='Exhaustion reduces all stats', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_sick', models.BooleanField(default=False)),
                ('sickness_severity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('immune_strength', models.FloatField(default=100.0, help_text='Immune system strength affects disease resistance and recovery', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('health_regen_rate', models.FloatField(default=1.0, help_text='HP regenerated per hour')),
                ('last_vital_update', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_status', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_type', models.CharField(choices=[('bandage', 'Bandage'), ('advanced_bandage', 'Bandage avancé'), ('splint', 'Attelle'), ('painkiller', 'Antidouleur'), ('antibiotic', 'Antibiotique'), ('antiviral', 'Antiviral'), ('antirad', 'Anti-radiation'), ('blood_bag', 'Poche de sang'), ('saline', 'Solution saline'), ('antidote', 'Antidote'), ('stimulant', 'Stimulant'), ('surgery_kit', 'Kit de chirurgie')], max_length=50)),
                ('heals_bleeding', models.BooleanField(default=False)),
                ('bleeding_stop_chance', models.FloatField(default=0.0, help_text='% chance to stop bleeding', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('heals_fractures', models.BooleanField(default=False)),
                ('restores_health', models.FloatField(default=0.0, help_text='HP restored instantly')),
                ('restores_blood', models.FloatField(default=0.0, help_text='Blood volume restored')),
                ('cures_infection', models.BooleanField(default=False)),
                ('infection_cure_rate', models.FloatField(default=0.0, help_text='% reduction in infection per use')),
                ('treats_disease', models.BooleanField(default=False)),
                ('disease_cure_rate', models.FloatField(default=0.0, help_text='% reduction in disease severity')),
                ('reduces_pain', models.BooleanField(default=False)),
                ('pain_reduction', models.FloatField(default=0.0, help_text='Pain level reduced')),
                ('pain_duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('restores_stamina', models.FloatField(default=0.0)),
                ('boosts_immune_system', models.FloatField(default=0.0, help_text='Temporary immune boost %')),
                ('requires_skill', models.BooleanField(default=False)),
                ('required_skill_level', models.IntegerField(default=0)),
                ('use_time_seconds', models.IntegerField(default=5, help_text='Time to apply/use')),
                ('success_rate', models.FloatField(default=100.0, help_text='Base success rate %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_properties', to='game.material')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_severity', models.FloatField(default=0.0, help_text='Current disease severity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_being_treated', models.BooleanField(default=False)),
                ('treatment_effectiveness', models.FloatField(default=0.0, help_text='How effective current treatment is (0-100%)')),
                ('contracted_at', models.DateTimeField(auto_now_add=True)),
                ('last_progression_update', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.disease')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='game.player')),
            ],
            options={
                'unique_together': {('player', 'disease')},
            },
        ),
        migrations.CreateModel(
            name='PlayerBodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_bleeding', models.BooleanField(default=False)),
                ('bleeding_severity', models.CharField(choices=[('none', 'Aucune'), ('minor', 'Mineure'), ('moderate', 'Modérée'), ('severe', 'Sévère'), ('critical', 'Critique')], default='none', max_length=20)),
                ('bleeding_rate', models.FloatField(default=0.0, help_text='HP lost per minute from bleeding')),
                ('is_fractured', models.BooleanField(default=False)),
                ('fracture_severity', models.CharField(choices=[('none', 'Aucune'), ('minor', 'Mineure'), ('moderate', 'Modérée'), ('severe', 'Sévère'), ('critical', 'Critique')], default='none', max_length=20)),
                ('is_infected', models.BooleanField(default=False)),
                ('infection_level', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pain_level', models.FloatField(default=0.0, help_text='Pain level (0-100), reduces player effectiveness', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_bandaged', models.BooleanField(default=False)),
                ('bandage_quality', models.FloatField(default=0.0, help_text='Quality of bandage (0-100)')),
                ('bandage_applied_at', models.DateTimeField(blank=True, null=True)),
                ('is_splinted', models.BooleanField(default=False)),
                ('splint_applied_at', models.DateTimeField(blank=True, null=True)),
                ('has_bullet', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.bodypart')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_parts', to='game.player')),
            ],
            options={
                'unique_together': {('player', 'body_part')},
            },
        ),
    ]
