# Generated by Django 4.2.25 on 2025-11-28 08:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_bodypart_disease_playerhealthstatus_medicalitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('has_petrol', models.BooleanField(default=True)),
                ('has_diesel', models.BooleanField(default=True)),
                ('has_electric', models.BooleanField(default=False)),
                ('petrol_price_per_liter', models.FloatField(default=1.5)),
                ('diesel_price_per_liter', models.FloatField(default=1.3)),
                ('electric_price_per_kwh', models.FloatField(default=0.3)),
                ('petrol_stock', models.FloatField(default=10000.0, help_text='Liters available')),
                ('diesel_stock', models.FloatField(default=10000.0, help_text='Liters available')),
                ('is_operational', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Station-service',
                'verbose_name_plural': 'Stations-service',
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('can_repair', models.BooleanField(default=True)),
                ('can_upgrade', models.BooleanField(default=True)),
                ('can_paint', models.BooleanField(default=False)),
                ('can_install_parts', models.BooleanField(default=True)),
                ('repair_cost_per_point', models.FloatField(default=1.0, help_text='Cost per durability point')),
                ('upgrade_cost_multiplier', models.FloatField(default=1.0)),
                ('mechanic_skill_level', models.IntegerField(default=50, help_text='Affects repair quality and available services', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('has_parts_inventory', models.BooleanField(default=True)),
                ('is_operational', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garages',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('bicycle', 'Vélo'), ('motorcycle', 'Moto'), ('car', 'Voiture'), ('truck', 'Camion'), ('van', 'Camionnette'), ('bus', 'Bus'), ('boat', 'Bateau'), ('helicopter', 'Hélicoptère'), ('atv', 'Quad/VTT')], max_length=20)),
                ('icon', models.TextField(default='🚗')),
                ('max_speed', models.IntegerField(default=60, help_text='Max speed in km/h')),
                ('acceleration', models.FloatField(default=5.0, help_text='Acceleration factor')),
                ('handling', models.FloatField(default=5.0, help_text='Handling quality (0-10)')),
                ('passenger_capacity', models.IntegerField(default=1, help_text='Number of passengers')),
                ('carry_capacity', models.FloatField(default=50.0, help_text='Cargo capacity in kg')),
                ('fuel_type', models.CharField(choices=[('none', 'Aucun'), ('petrol', 'Essence'), ('diesel', 'Diesel'), ('electric', 'Électrique'), ('hybrid', 'Hybride')], default='petrol', max_length=20)),
                ('fuel_tank_size', models.FloatField(default=50.0, help_text='Fuel tank size in liters')),
                ('fuel_consumption', models.FloatField(default=8.0, help_text='Liters per 100km')),
                ('energy_cost_multiplier', models.FloatField(default=0.5, help_text='Multiplier for player energy cost when using vehicle')),
                ('max_durability', models.IntegerField(default=1000)),
                ('maintenance_interval', models.IntegerField(default=5000, help_text='Distance in km before maintenance needed')),
                ('can_offroad', models.BooleanField(default=False)),
                ('can_water', models.BooleanField(default=False)),
                ('requires_road', models.BooleanField(default=True)),
                ('noise_level', models.IntegerField(default=50, help_text='How loud the vehicle is (affects stealth)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weather_protection', models.IntegerField(default=50, help_text='Protection from rain/cold', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rarity', models.CharField(choices=[('common', 'Commun'), ('uncommon', 'Peu commun'), ('rare', 'Rare'), ('epic', 'Épique'), ('legendary', 'Légendaire')], default='common', max_length=20)),
                ('base_value', models.IntegerField(default=1000, help_text='Base monetary value')),
            ],
            options={
                'verbose_name': 'Type de véhicule',
                'verbose_name_plural': 'Types de véhicules',
            },
        ),
        migrations.AlterModelOptions(
            name='playervehicle',
            options={'verbose_name': 'Véhicule du joueur', 'verbose_name_plural': 'Véhicules des joueurs'},
        ),
        migrations.RemoveField(
            model_name='playervehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='playervehicle',
            name='durability_current',
        ),
        migrations.RemoveField(
            model_name='playervehicle',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='acquired_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='armor_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='capacity_upgrade',
            field=models.FloatField(default=0.0, help_text='Additional cargo capacity'),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='current_fuel',
            field=models.FloatField(default=0.0, help_text='Current fuel in liters'),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='distance_since_maintenance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='fuel_efficiency_upgrade',
            field=models.FloatField(default=0.0, help_text='% reduction in fuel consumption'),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='has_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='has_turbo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='last_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='needs_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='overall_durability',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='parked_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='parked_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='speed_upgrade',
            field=models.FloatField(default=0.0, help_text='% increase in max speed'),
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='total_distance_km',
            field=models.FloatField(default=0.0, help_text='Total distance traveled'),
        ),
        migrations.AlterField(
            model_name='playervehicle',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_vehicles', to='game.player'),
        ),
        migrations.CreateModel(
            name='VehiclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('part_type', models.CharField(choices=[('engine', 'Moteur'), ('transmission', 'Transmission'), ('wheels', 'Roues'), ('battery', 'Batterie'), ('fuel_tank', 'Réservoir'), ('radiator', 'Radiateur'), ('brakes', 'Freins'), ('suspension', 'Suspension'), ('body', 'Carrosserie'), ('windshield', 'Pare-brise'), ('lights', 'Feux'), ('seats', 'Sièges'), ('electrical', 'Système électrique'), ('exhaust', 'Échappement')], max_length=20)),
                ('description', models.TextField()),
                ('max_durability', models.IntegerField(default=100)),
                ('weight', models.FloatField(default=10.0, help_text='Weight in kg')),
                ('speed_modifier', models.FloatField(default=0.0, help_text='Speed bonus/penalty')),
                ('fuel_efficiency_modifier', models.FloatField(default=0.0, help_text='Fuel consumption modifier')),
                ('handling_modifier', models.FloatField(default=0.0)),
                ('rarity', models.CharField(choices=[('common', 'Commun'), ('uncommon', 'Peu commun'), ('rare', 'Rare'), ('epic', 'Épique'), ('legendary', 'Légendaire')], default='common', max_length=20)),
                ('value', models.IntegerField(default=100, help_text='Monetary value')),
                ('compatible_vehicles', models.ManyToManyField(related_name='parts', to='game.vehicletype')),
            ],
            options={
                'verbose_name': 'Pièce de véhicule',
                'verbose_name_plural': 'Pièces de véhicules',
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('repair', 'Réparation'), ('service', 'Entretien'), ('part_replacement', 'Remplacement de pièce'), ('upgrade', 'Amélioration'), ('refuel', 'Ravitaillement')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(default=0, help_text='Cost in money')),
                ('durability_restored', models.IntegerField(default=0)),
                ('fuel_added', models.FloatField(default=0.0)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('parts_replaced', models.ManyToManyField(blank=True, to='game.vehiclepart')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player')),
                ('player_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='game.playervehicle')),
            ],
            options={
                'verbose_name': "Journal d'entretien",
                'verbose_name_plural': "Journaux d'entretien",
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='playervehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.vehicletype'),
        ),
        migrations.CreateModel(
            name='PlayerVehiclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_durability', models.IntegerField(default=100)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('is_damaged', models.BooleanField(default=False)),
                ('is_broken', models.BooleanField(default=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.vehiclepart')),
                ('player_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_parts', to='game.playervehicle')),
            ],
            options={
                'verbose_name': 'Pièce de véhicule installée',
                'verbose_name_plural': 'Pièces de véhicules installées',
                'unique_together': {('player_vehicle', 'part')},
            },
        ),
    ]
