# Generated by Django 4.2.25 on 2025-11-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_fuelstation_garage_vehicletype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bladder_fullness',
            field=models.FloatField(default=0.0, help_text='0-100%'),
        ),
        migrations.AddField(
            model_name='player',
            name='body_fat',
            field=models.FloatField(default=15.0, help_text='Body fat in kg'),
        ),
        migrations.AddField(
            model_name='player',
            name='body_weight',
            field=models.FloatField(default=70.0, help_text='Body weight in kg'),
        ),
        migrations.AddField(
            model_name='player',
            name='bowel_fullness',
            field=models.FloatField(default=0.0, help_text='0-100%'),
        ),
        migrations.AddField(
            model_name='player',
            name='calories_stored',
            field=models.FloatField(default=2000.0, help_text='Current caloric energy (kcal)'),
        ),
        migrations.AddField(
            model_name='player',
            name='carbs_stored',
            field=models.FloatField(default=300.0, help_text='Carbohydrate reserves in grams'),
        ),
        migrations.AddField(
            model_name='player',
            name='energy_regen_modifier',
            field=models.FloatField(default=1.0, help_text='Multiplier for energy regeneration'),
        ),
        migrations.AddField(
            model_name='player',
            name='fat_stored',
            field=models.FloatField(default=150.0, help_text='Fat reserves in grams'),
        ),
        migrations.AddField(
            model_name='player',
            name='intestine_contents',
            field=models.FloatField(default=0.0, help_text='Food in intestines (0-100%)'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_bloated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_dehydrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_hungry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_overfed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_starving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_thirsty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='last_calorie_burn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_metabolism_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='max_calories',
            field=models.FloatField(default=3000.0, help_text='Maximum caloric storage'),
        ),
        migrations.AddField(
            model_name='player',
            name='max_water_volume',
            field=models.FloatField(default=45.0, help_text='Maximum healthy water volume'),
        ),
        migrations.AddField(
            model_name='player',
            name='muscle_mass',
            field=models.FloatField(default=30.0, help_text='Muscle mass in kg'),
        ),
        migrations.AddField(
            model_name='player',
            name='needs_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='protein_stored',
            field=models.FloatField(default=100.0, help_text='Protein reserves in grams'),
        ),
        migrations.AddField(
            model_name='player',
            name='stamina_modifier',
            field=models.FloatField(default=1.0, help_text='Multiplier for stamina'),
        ),
        migrations.AddField(
            model_name='player',
            name='stomach_fullness',
            field=models.FloatField(default=0.0, help_text='How full stomach is (0-100%)'),
        ),
        migrations.AddField(
            model_name='player',
            name='strength_modifier',
            field=models.FloatField(default=1.0, help_text='Multiplier for strength'),
        ),
        migrations.AddField(
            model_name='player',
            name='water_volume',
            field=models.FloatField(default=42.0, help_text='Body water in liters (70kg person ~60% water)'),
        ),
    ]
