# Generated by Django 5.2.8 on 2025-11-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_player_bladder_fullness_player_body_fat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='👤', max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=30)),
                ('attack', models.IntegerField(default=8)),
                ('defense', models.IntegerField(default=2)),
                ('xp_reward', models.IntegerField(default=15)),
                ('encounter_rate', models.FloatField(default=0.2, help_text='Probability of encountering (0.0-1.0)')),
                ('aggression_level', models.CharField(choices=[('passive', "Passif - N'attaque jamais"), ('defensive', 'Défensif - Attaque si provoqué'), ('neutral', 'Neutre - Peut attaquer'), ('aggressive', 'Agressif - Attaque souvent'), ('very_aggressive', 'Très agressif - Attaque toujours')], default='neutral', max_length=20)),
                ('money_min', models.IntegerField(default=5)),
                ('money_max', models.IntegerField(default=20)),
                ('biomes_json', models.TextField(default='[]', help_text='List of biomes where this enemy spawns')),
                ('equipment_json', models.TextField(default='{}', help_text='Equipment carried by enemy')),
                ('inventory_json', models.TextField(default='{}', help_text='Items in enemy inventory')),
                ('min_level_required', models.IntegerField(default=1, help_text='Player level required to encounter')),
                ('time_of_day', models.CharField(choices=[('any', 'Anytime'), ('day', 'Day only'), ('night', 'Night only')], default='any', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('victory', 'Victory'), ('fled', 'Fled'), ('defeated', 'Defeated')], default='active', max_length=20)),
                ('enemy_attacked_first', models.BooleanField(default=False)),
                ('enemy_current_health', models.IntegerField()),
                ('damage_dealt', models.IntegerField(default=0)),
                ('damage_taken', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('loot_json', models.TextField(default='[]', help_text='Items looted from enemy')),
                ('money_looted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mapcell')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='game.player')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.randomenemy')),
            ],
        ),
    ]
